/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStudy {
  'title' : string,
  'description' : string,
  'outcomeMetrics' : string,
  'category' : string,
  'location' : string,
}
export interface ContactForm {
  'contactName' : string,
  'email' : string,
  'message' : string,
  'companyName' : string,
  'phone' : string,
  'budgetRange' : string,
}
export interface ImpactMetrics {
  'partnerCompanies' : bigint,
  'statesCovered' : bigint,
  'totalLivesImpacted' : bigint,
  'projectsCompleted' : bigint,
}
export interface NewsletterSignup { 'email' : string, 'companyName' : string }
export interface ProjectUpdate {
  'id' : bigint,
  'status' : string,
  'projectName' : string,
  'description' : string,
  'fundUtilization' : bigint,
}
export interface _SERVICE {
  'addCaseStudy' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addProjectUpdate' : ActorMethod<[string, string, bigint, string], undefined>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllNewsletterSignups' : ActorMethod<[], Array<NewsletterSignup>>,
  'getCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getCaseStudiesByTitle' : ActorMethod<[], Array<CaseStudy>>,
  'getContactFormsByEmail' : ActorMethod<[], Array<ContactForm>>,
  'getImpactMetrics' : ActorMethod<[], ImpactMetrics>,
  'getProjectUpdates' : ActorMethod<[], Array<ProjectUpdate>>,
  'signupNewsletter' : ActorMethod<[string, string], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateImpactMetrics' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];