/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactForm = IDL.Record({
  'contactName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
});
export const NewsletterSignup = IDL.Record({
  'email' : IDL.Text,
  'companyName' : IDL.Text,
});
export const CaseStudy = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'outcomeMetrics' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const ImpactMetrics = IDL.Record({
  'partnerCompanies' : IDL.Nat,
  'statesCovered' : IDL.Nat,
  'totalLivesImpacted' : IDL.Nat,
  'projectsCompleted' : IDL.Nat,
});
export const ProjectUpdate = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'projectName' : IDL.Text,
  'description' : IDL.Text,
  'fundUtilization' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCaseStudy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addProjectUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllNewsletterSignups' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSignup)],
      ['query'],
    ),
  'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getCaseStudiesByTitle' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getContactFormsByEmail' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getImpactMetrics' : IDL.Func([], [ImpactMetrics], ['query']),
  'getProjectUpdates' : IDL.Func([], [IDL.Vec(ProjectUpdate)], ['query']),
  'signupNewsletter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateImpactMetrics' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactForm = IDL.Record({
    'contactName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
  });
  const NewsletterSignup = IDL.Record({
    'email' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const CaseStudy = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'outcomeMetrics' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const ImpactMetrics = IDL.Record({
    'partnerCompanies' : IDL.Nat,
    'statesCovered' : IDL.Nat,
    'totalLivesImpacted' : IDL.Nat,
    'projectsCompleted' : IDL.Nat,
  });
  const ProjectUpdate = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'projectName' : IDL.Text,
    'description' : IDL.Text,
    'fundUtilization' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCaseStudy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addProjectUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllNewsletterSignups' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSignup)],
        ['query'],
      ),
    'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getCaseStudiesByTitle' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getContactFormsByEmail' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getImpactMetrics' : IDL.Func([], [ImpactMetrics], ['query']),
    'getProjectUpdates' : IDL.Func([], [IDL.Vec(ProjectUpdate)], ['query']),
    'signupNewsletter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateImpactMetrics' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };