/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImpactMetrics {
    partnerCompanies: bigint;
    statesCovered: bigint;
    totalLivesImpacted: bigint;
    projectsCompleted: bigint;
}
export interface ProjectUpdate {
    id: bigint;
    status: string;
    projectName: string;
    description: string;
    fundUtilization: bigint;
}
export interface ContactForm {
    contactName: string;
    email: string;
    message: string;
    companyName: string;
    phone: string;
    budgetRange: string;
}
export interface NewsletterSignup {
    email: string;
    companyName: string;
}
export interface CaseStudy {
    title: string;
    description: string;
    outcomeMetrics: string;
    category: string;
    location: string;
}
export interface backendInterface {
    addCaseStudy(title: string, category: string, description: string, location: string, outcomeMetrics: string): Promise<void>;
    addProjectUpdate(projectName: string, status: string, fundUtilization: bigint, description: string): Promise<void>;
    getAllContactForms(): Promise<Array<ContactForm>>;
    getAllNewsletterSignups(): Promise<Array<NewsletterSignup>>;
    getCaseStudies(): Promise<Array<CaseStudy>>;
    getCaseStudiesByTitle(): Promise<Array<CaseStudy>>;
    getContactFormsByEmail(): Promise<Array<ContactForm>>;
    getImpactMetrics(): Promise<ImpactMetrics>;
    getProjectUpdates(): Promise<Array<ProjectUpdate>>;
    signupNewsletter(email: string, companyName: string): Promise<void>;
    submitContactForm(companyName: string, contactName: string, email: string, phone: string, message: string, budgetRange: string): Promise<void>;
    updateImpactMetrics(totalLivesImpacted: bigint, projectsCompleted: bigint, partnerCompanies: bigint, statesCovered: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCaseStudy(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCaseStudy(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCaseStudy(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addProjectUpdate(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectUpdate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectUpdate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactForms();
            return result;
        }
    }
    async getAllNewsletterSignups(): Promise<Array<NewsletterSignup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsletterSignups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsletterSignups();
            return result;
        }
    }
    async getCaseStudies(): Promise<Array<CaseStudy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseStudies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseStudies();
            return result;
        }
    }
    async getCaseStudiesByTitle(): Promise<Array<CaseStudy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseStudiesByTitle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseStudiesByTitle();
            return result;
        }
    }
    async getContactFormsByEmail(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactFormsByEmail();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactFormsByEmail();
            return result;
        }
    }
    async getImpactMetrics(): Promise<ImpactMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getImpactMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImpactMetrics();
            return result;
        }
    }
    async getProjectUpdates(): Promise<Array<ProjectUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectUpdates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectUpdates();
            return result;
        }
    }
    async signupNewsletter(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signupNewsletter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signupNewsletter(arg0, arg1);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateImpactMetrics(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImpactMetrics(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImpactMetrics(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
